// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVnAocxJDmkeb-l9N_r-Zhf29C7yc_u5c',
    appId: '1:198466427601:web:49b76d1378b01fc48e43f0',
    messagingSenderId: '198466427601',
    projectId: 'bookingtourapp-7ed7d',
    authDomain: 'bookingtourapp-7ed7d.firebaseapp.com',
    storageBucket: 'bookingtourapp-7ed7d.appspot.com',
    measurementId: 'G-MWZPSMF4MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsiJKOzJqbOfS0U9jKgWa95EYvIEU7eR4',
    appId: '1:198466427601:android:804b008c58b135f48e43f0',
    messagingSenderId: '198466427601',
    projectId: 'bookingtourapp-7ed7d',
    storageBucket: 'bookingtourapp-7ed7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnVf28_TMemYv9UgMR574avB-Uccirrc',
    appId: '1:198466427601:ios:000c30d0ba252ac58e43f0',
    messagingSenderId: '198466427601',
    projectId: 'bookingtourapp-7ed7d',
    storageBucket: 'bookingtourapp-7ed7d.appspot.com',
    androidClientId: '198466427601-32itfkv87kv5vp64urv76jg4m8po4ei4.apps.googleusercontent.com',
    iosClientId: '198466427601-j5t69bfaqeuctifh1ubeqiaepp5v97aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnVf28_TMemYv9UgMR574avB-Uccirrc',
    appId: '1:198466427601:ios:000c30d0ba252ac58e43f0',
    messagingSenderId: '198466427601',
    projectId: 'bookingtourapp-7ed7d',
    storageBucket: 'bookingtourapp-7ed7d.appspot.com',
    androidClientId: '198466427601-32itfkv87kv5vp64urv76jg4m8po4ei4.apps.googleusercontent.com',
    iosClientId: '198466427601-j5t69bfaqeuctifh1ubeqiaepp5v97aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlhgu51ZXPr1RB6sMwU_I5pslNpd6wlc',
    appId: '1:198466427601:web:d9c526051c9f81218e43f0',
    messagingSenderId: '198466427601',
    projectId: 'bookingtourapp-7ed7d',
    authDomain: 'bookingtourapp-7ed7d.firebaseapp.com',
    storageBucket: 'bookingtourapp-7ed7d.appspot.com',
    measurementId: 'G-M9V1CVECL9',
  );

}